'use client'

// import ReactQueryProvider from '@/providers/TanstackProvider';
// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ToastContainer } from 'react-toastify';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';

// imported from template in GitHub 
import ScrollToTop from "@/components/common/ScrollTop";
import "../../public/assets/scss/index.scss"
import {Provider} from "react-redux"
import {store} from "./store/store"

if (typeof window !== "undefined") {
  require("bootstrap/dist/js/bootstrap");
}

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:400,400i,500,600,700&display=swap" />
        <link rel="icon" href="./favicon.ico" />
      </head>

      <body className={inter.className}>
        <Provider store={store}>
          {children}
          <ToastContainer />
        </Provider>
        
        <ScrollToTop/>
      </body>
    </html>
  );
}
